In [1]:
import pandas as pd
import ast

In [2]:
# Load the datasets
credits = pd.read_csv(r"D:\DATA FILE\tmdb_5000_credits.csv\tmdb_5000_credits.csv")
movies= pd.read_csv(r"D:\DATA FILE\tmdb_5000_movies.csv\tmdb_5000_movies.csv")

In [3]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [4]:
credits.shape

(4803, 4)

In [5]:
movies.shape

(4803, 20)

In [6]:
# Merge the datasets on the common column 'title'
merged = pd.merge(movies, credits, on='title')

In [7]:
merged.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
merged.head(1)['cast']

0    [{"cast_id": 242, "character": "Jake Sully", "...
Name: cast, dtype: object

In [9]:
# Select only the specified columns
selected_columns = ['genres', 'keywords', 'overview', 'title', 'movie_id', 'cast', 'crew']
final = merged[selected_columns].copy()

In [10]:
# Function to extract names from the list of dictionaries
def extract_names(column_str, key='name', limit=None, filter_by=None, filter_value=None):
    try:
        items = ast.literal_eval(column_str)
        if filter_by and filter_value:
            items = [item for item in items if item.get(filter_by) == filter_value]
        names = [item[key] for item in items]
        if limit:
            names = names[:limit]
        return names
    except (ValueError, SyntaxError):
        return []

In [11]:
# Apply the function to the relevant columns using .loc to avoid SettingWithCopyWarning
final.loc[:, 'genres'] = final['genres'].apply(lambda x: extract_names(x, 'name'))
final.loc[:, 'keywords'] = final['keywords'].apply(lambda x: extract_names(x, 'name'))
final.loc[:, 'cast'] = final['cast'].apply(lambda x: extract_names(x, 'name', limit=3))  # Limit to first three names
final.loc[:, 'crew'] = final['crew'].apply(lambda x: extract_names(x, 'name', filter_by='job', filter_value='Director'))  # Only Director's name

In [12]:
# Display the first few rows of the final dataframe to verify
final.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [13]:
# Convert lists to strings to make them hashable
final['genres'] = final['genres'].apply(lambda x: ', '.join(x))
final['keywords'] = final['keywords'].apply(lambda x: ', '.join(x))
final['cast'] = final['cast'].apply(lambda x: ', '.join(x))
final['crew'] = final['crew'].apply(lambda x: ', '.join(x))

In [14]:
final.isnull().sum()

genres      0
keywords    0
overview    3
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [15]:
final = final.dropna()

In [16]:
final.isnull().sum()

genres      0
keywords    0
overview    0
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [17]:
final.duplicated().sum()

0

In [18]:
final.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"Sam Worthington, Zoe Saldana, Sigourney Weaver",James Cameron
1,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"Johnny Depp, Orlando Bloom, Keira Knightley",Gore Verbinski
2,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"Daniel Craig, Christoph Waltz, LÃ©a Seydoux",Sam Mendes
3,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"Christian Bale, Michael Caine, Gary Oldman",Christopher Nolan
4,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...","John Carter is a war-weary, former military ca...",John Carter,49529,"Taylor Kitsch, Lynn Collins, Samantha Morton",Andrew Stanton

In [19]:
final['cast'][0]

'Sam Worthington, Zoe Saldana, Sigourney Weaver'

In [20]:
# Convert the rest of the columns to lower case
final['overview'] = final['overview'].str.lower()
final['title'] = final['title'].str.lower()
final['genres'] = final['genres'].str.lower()
final['cast'] = final['cast'].str.lower()
final['keywords'] = final['keywords'].str.lower()

In [21]:
final.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"action, adventure, fantasy, science fiction","culture clash, future, space war, space colony...","in the 22nd century, a paraplegic marine is di...",avatar,19995,"sam worthington, zoe saldana, sigourney weaver",James Cameron
1,"adventure, fantasy, action","ocean, drug abuse, exotic island, east india t...","captain barbossa, long believed to be dead, ha...",pirates of the caribbean: at world's end,285,"johnny depp, orlando bloom, keira knightley",Gore Verbinski
2,"action, adventure, crime","spy, based on novel, secret agent, sequel, mi6...",a cryptic message from bondâ€™s past sends him o...,spectre,206647,"daniel craig, christoph waltz, lÃ©a seydoux",Sam Mendes
3,"action, crime, drama, thriller","dc comics, crime fighter, terrorist, secret id...",following the death of district attorney harve...,the dark knight rises,49026,"christian bale, michael caine, gary oldman",Christopher Nolan
4,"action, adventure, science fiction","based on novel, mars, medallion, space travel,...","john carter is a war-weary, former military ca...",john carter,49529,"taylor kitsch, lynn collins, samantha morton",Andrew Stanton

In [22]:
'''
# Function to remove spaces within each name in the cast column and join them with commas
def remove_spaces_in_cast(cast_list):
    return ''.join([name.replace(' ', '') for name in cast_list])

# Apply the remove_spaces_in_cast function to the cast column
final['cast'] = final['cast'].apply(remove_spaces_in_cast)
'''

"\n# Function to remove spaces within each name in the cast column and join them with commas\ndef remove_spaces_in_cast(cast_list):\n    return ''.join([name.replace(' ', '') for name in cast_list])\n\n# Apply the remove_spaces_in_cast function to the cast column\nfinal['cast'] = final['cast'].apply(remove_spaces_in_cast)\n"

In [23]:
final.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"action, adventure, fantasy, science fiction","culture clash, future, space war, space colony...","in the 22nd century, a paraplegic marine is di...",avatar,19995,"sam worthington, zoe saldana, sigourney weaver",James Cameron
1,"adventure, fantasy, action","ocean, drug abuse, exotic island, east india t...","captain barbossa, long believed to be dead, ha...",pirates of the caribbean: at world's end,285,"johnny depp, orlando bloom, keira knightley",Gore Verbinski
2,"action, adventure, crime","spy, based on novel, secret agent, sequel, mi6...",a cryptic message from bondâ€™s past sends him o...,spectre,206647,"daniel craig, christoph waltz, lÃ©a seydoux",Sam Mendes
3,"action, crime, drama, thriller","dc comics, crime fighter, terrorist, secret id...",following the death of district attorney harve...,the dark knight rises,49026,"christian bale, michael caine, gary oldman",Christopher Nolan
4,"action, adventure, science fiction","based on novel, mars, medallion, space travel,...","john carter is a war-weary, former military ca...",john carter,49529,"taylor kitsch, lynn collins, samantha morton",Andrew Stanton

In [24]:
final['cast'][0]

'sam worthington, zoe saldana, sigourney weaver'

In [25]:
final['tags'] = final['genres'] + final['keywords'] + final['overview'] + final['cast']

In [26]:
final.head()

,genres,keywords,overview,title,movie_id,cast,crew,tags
0,"action, adventure, fantasy, science fiction","culture clash, future, space war, space colony...","in the 22nd century, a paraplegic marine is di...",avatar,19995,"sam worthington, zoe saldana, sigourney weaver",James Cameron,"action, adventure, fantasy, science fictioncul..."
1,"adventure, fantasy, action","ocean, drug abuse, exotic island, east india t...","captain barbossa, long believed to be dead, ha...",pirates of the caribbean: at world's end,285,"johnny depp, orlando bloom, keira knightley",Gore Verbinski,"adventure, fantasy, actionocean, drug abuse, e..."
2,"action, adventure, crime","spy, based on novel, secret agent, sequel, mi6...",a cryptic message from bondâ€™s past sends him o...,spectre,206647,"daniel craig, christoph waltz, lÃ©a seydoux",Sam Mendes,"action, adventure, crimespy, based on novel, s..."
3,"action, crime, drama, thriller","dc comics, crime fighter, terrorist, secret id...",following the death of district attorney harve...,the dark knight rises,49026,"christian bale, michael caine, gary oldman",Christopher Nolan,"action, crime, drama, thrillerdc comics, crime..."
4,"action, adventure, science fiction","based on novel, mars, medallion, space travel,...","john carter is a war-weary, former military ca...",john carter,49529,"taylor kitsch, lynn collins, samantha morton",Andrew Stanton,"action, adventure, science fictionbased on nov..."

In [27]:
# Select only the specified columns
selected = ['title', 'movie_id', 'crew','tags']
final = final[selected].copy()

In [28]:
final['tags'][0]

'action, adventure, fantasy, science fictionculture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3din the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.sam worthington, zoe saldana, sigourney weaver'

In [47]:
final.to_csv('merged.csv', index=False)

In [29]:
import nltk

In [30]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [31]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [32]:
final['tags'] = final['tags'].apply(stem)

In [33]:
final['tags'][0]

'action, adventure, fantasy, scienc fictioncultur clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3din the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.sam worthington, zoe saldana, sigourney weaver'

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [36]:
text_vector = cv.fit_transform(final['tags']).toarray()

In [37]:
text_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
text_vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1930',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990',
 '19th',
 '20',
 '200',
 '20th',
 '21st',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '3da',
 '3dthe',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abigail',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abraham',
 'abroad',
 'abus',
 'abuse',
 'academi',
 'accent',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'accused',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adams',
 'adapt',
 'adaptation',
 'add',
 'addict',
 'addiction',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'adoption',
 'ador',
 'adrian',
 'adrien',
 'adult',
 'adultery',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advice',
 'advis',
 'affair',
 'affect',
 'affection',
 'affleck',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'aftercreditsstingera',
 'afterlife',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agenta',
 'agents',
 'ages',
 'aggress',
 'aging',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan',
 'aids',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airplan',
 'airplane',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alba',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alec',
 'alex',
 'alexand',
 'alexi',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alicia',
 'alien',
 'aliv',
 'alive',
 'allan',
 'allen',
 'alli',
 'allianc',
 'allison',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'ambit',
 'ambiti',
 'ambition',
 'ambulance',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amy',
 'ana',
 'analyst',
 'anarch',
 'ancient',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'andrews',
 'android',
 'andrÃ©',
 'andy',
 'angarano',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'anger',
 'angri',
 'angst',
 'ani',
 'anim',
 'animal',
 'animals',
 'animation',
 'aniston',
 'ann',
 'anna',
 'annett',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'anthology',
 'anthoni',
 'anthropomorphism',
 'anti',
 'antic',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalypse',
 'apocalypt',
 'apocalyptic',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'apprentice',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arkin',
 'arm',
 'armi',
 'armor',
 'armstrong',
 'army',
 'arnold',
 'arquette',
 'arrang',
 'arrest',
 'arriv',
 'arrow',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artist',
 'arts',
 'ash',
 'ashley',
 'ashton',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assassination',
 'assault',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'athlete',
 'atlant',
 'atom',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'attraction',
 'audienc',
 'audit',
 'audition',
 'audrey',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'authority',
 'autism',
 'auto',
 'automobil',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'award',
 'away',
 'awri',
 'awry',
 'axe',
 'aykroyd',
 'azaria',
 'babi',
 'baby',
 'bachchan',
 'bachelor',
 'backdrop',
 'background',
 'bacon',
 'bad',
 'bag',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'baldwin',
 'bale',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'bana',
 'band',
 'banderas',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'banks',
 'bar',
 'barbara',
 'bardem',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'barrymore',
 'bas',
 'base',
 'basebal',
 'baseball',
 'basement',
 'basinger',
 'basketbal',
 'basketball',
 'bassett',
 'bat',
 'bate',
 'bateman',
 'bath',
 'bathroom',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bean',
 'bear',
 'beard',
 'beast',
 'beat',
 'beating',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'beckinsale',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'belle',
 'bello',
 'belong',
 'belov',
 'belt',
 'belushi',
 'ben',
 'bend',
 'beneath',
 'benedict',
 'benefit',
 'benicio',
 'bening',
 'benjamin',
 'bennett',
 'bent',
 'bentley',
 'berlin',
 'bernal',
 'berni',
 'berri',
 'berry',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'bett',
 'bettany',
 'better',
 'betti',
 'beverli',
 'bible',
 'biblic',
 'bid',
 'biehn',
 'biel',
 'big',
 'bigger',
 'biggest',
 'biggs',
 'bike',
 'biker',
 'bikini',
 'bil',
 'billi',
 'billion',
 'billionair',
 'biography',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blair',
 'blake',
 'blame',
 'blanchett',
 'bledel',
 'blend',
 'bless',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blonde',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blue',
 'blunt',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bone',
 'bonham',
 'bonni',
 'book',
 'booth',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bosworth',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradford',
 'bradley',
 'brain',
 'branagh',
 'brand',
 'brando',
 'brandon',
 'bratt',
 'brave',
 'bravery',
 'brazil',
 'break',
 'breakdown',
 'breath',
 'breed',
 'brendan',
 'brent',
 'breslin',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'bridge',
 'bridges',
 'bridget',
 'brie',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britt',
 'brittani',
 'broadbent',
 'broadcast',
 'broadway',
 'broderick',
 'brody',
 'broke',
 'broken',
 'broker',
 'brolin',
 'brook',
 'brooklyn',
 'brooks',
 'broom',
 'brosnan',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruc',
 'bruce',
 'brutal',
 'brutality',
 'bryan',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bullock',
 'bully',
 'bullying',
 'bumbl',
 'burglar',
 'buri',
 'burk',
 'burn',
 'burns',
 'burstyn',
 'burt',
 'burton',
 'bus',
 'buscemi',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'byrn',
 'byrne',
 'caan',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'caine',
 'cal',
 'california',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannibal',
 'cannon',
 'capabl',
 'capitalism',
 'captain',
 'captiv',
 'captive',
 'captur',
 'capture',
 'car',
 'card',
 'care',
 'career',
 'carell',
 'carey',
 'cargo',
 'cari',
 'caribbean',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carol',
 'carolin',
 'carolina',
 'carrey',
 'carri',
 'carrie',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cast',
 'castle',
 'casual',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate',
 'catherin',
 'cathol',
 'catholic',
 'catholicism',
 'cattl',
 'caught',
 'caus',
 'cave',
 'caviezel',
 'cedric',
 'celebr',
 'celebration',
 'celebrity',
 'cell',
 'cemetery',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chad',
 'chain',
 'chair',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliz',
 'charlott',
 'charm',
 'chase',
 'chastain',
 'chat',
 'chauffeur',
 'chazz',
 'cheat',
 'cheating',
 'check',
 'chef',
 'chelsea',
 'chemic',
 'chen',
 'chestnut',
 'chevi',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chiwetel',
 'chloe',
 'chloÃ«',
 'choic',
 'choice',
 'choir',
 'choos',
 'chosen',
 'chow',
 'chri',
 'christ',
 'christensen',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡n',
 'cigar',
 'cigarett',
 'cillian',
 'cinema',
 'cinemat',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'clair',
 'clan',
 'clark',
 'clarke',
 'clarkson',
 'clash',
 'class',
 'classic',
 'classmat',
 'classmates',
 'classroom',
 'claud',
 'claudia',
 'claus',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliff',
 'climat',
 'climb',
 'climbing',
 'clint',
 'clive',
 'clock',
 'clone',
 'cloning',
 'clooney',
 'close',
 'closer',
 'closet',
 'cloud',
 'clown',
 'club',
 'clue',
 'clutch',
 'coach',
 'coal',
 'coast',
 'cocain',
 'cocaine',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'cole',
 'coleman',
 'colin',
 'collaps',
 'collar',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collette',
 'collid',
 'collins',
 'collis',
 'colm',
 'colombia',
 'colonel',
 'coloni',
 'colony',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comedya',
 'comedygay',
 'comedyholiday',
 'comedyindepend',
 'comedynew',
 'comedysex',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'command',
 'commando',
 'commiss',
 'commit',
 'commitment',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compton',
 'compuls',
 'comput',
 'computer',
 'conan',
 'concentr',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confid',
 'conflict',
 'confront',
 'confus',
 'congress',
 'connect',
 'connery',
 'conni',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similar = cosine_similarity(text_vector)

In [42]:
sorted(list(enumerate(similar[0])),reverse = True, key=lambda x:x[1])[1:6]

[(2409, 0.4507106573161516),
 (3162, 0.4086128521889546),
 (838, 0.40336993708101765),
 (2021, 0.38575365034016906),
 (1537, 0.3828911654062392)]

In [43]:
def recommend(movie):
    # Convert the input movie title to lower case
    movie = movie.lower()
    
    # Check if the movie exists in the DataFrame
    if movie not in final['title'].values:
        print(f"Movie '{movie}' not found in the dataset.")
        return
    
    # Find the index of the movie in the DataFrame
    movie_index = final[final['title'] == movie].index[0]
    
    # Get the similarity scores for the movie
    distance = similar[movie_index]
    
    # Sort the movies based on similarity scores and get the indices of the top 5 similar movies
    movie_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x: x[1])[1:6]

    # Print the titles of the recommended movies
    for i in movie_list:
        print(final.iloc[i[0]]['title'])

In [44]:
recommend('batman begins')

the dark knight
batman
batman
the dark knight rises
batman & robin

In [45]:
import pickle

In [46]:
pickle.dump(final.to_dict(),open('movies_dict.pkl','wb'))

In [48]:
# Assuming 'similar' is your similarity matrix
with open('similarity_matrix.pkl', 'wb') as f:
    pickle.dump(similar, f)